apiVersion: v1
kind: Service
metadata:
  name: survey-app
  namespace: python-app
  labels:
    app: survey-app
spec:
  selector:
    app: survey-app  # This should match the labels in your Deployment Pods
  type: NodePort
  ports:
    - port: 8005          # The port exposed by the service
      targetPort: 8005    # The port on the Pod that the service will forward traffic to

    
